name: Deploy to prod-gcp
on:
  release:
    types: [published]

jobs:
  deploy-prod:
    name: Deploy to prod-gcp
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get release tag
        env:
          VERSION_TAG: ${{ github.event.release.tag_name }}
        run: |
          APPLICATION=$(echo $GITHUB_REPOSITORY | cut -d "/" -f 2)
          IMAGE=docker.pkg.github.com/$GITHUB_REPOSITORY/$APPLICATION:$VERSION_TAG
          echo "::set-env name=IMAGE::$IMAGE"
          echo $IMAGE
      - name: Deploy to prod-gcp
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: .nais/nais.yaml
          VARS: .nais/prod.json
      - name: Post-production
        uses: navikt/digihot-deploy/actions/post-production@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
